### ISSUE TITLE
Document the Open Liberty container image tags

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/docs#5233] opened 2022-02-24 15:45 UTC
Required for openliberty.io issue [Update docker pull to include icr.io](https://github.com/openliberty/openliberty.io/issues/2524).

openliberty.io would like to promote [IBM Cloud Container Registry](https://www.ibm.com/cloud/container-registry) for downloading Open Liberty container images.

The intent is to have new documentation describing each of the "unversioned" container image tags (e.g. `beta` `beta-java11` `kernel-slim`, `kernel-slim-java8-openj9`) to help users choose an image that best suits their development needs.

**Comment by dmuelle** [comment] 2022-03-03 20:12
I just checked with @leochr and he confirmed that the OL beta images are only available from Docker hub at the moment. Based on Slack comments from @NottyCode in #was-open-liberty-site, we need to get the betas added to ICR rather than pointing to Docker Hub from the container image doc.

**Comment by dmuelle** [comment] 2022-04-13 14:01
https://github.com/OpenLiberty/ci.docker/blob/master/docs/icr-images.md

**Comment by dmuelle** [comment] 2022-05-04 13:45
https://github.com/OpenLiberty/ci.docker/issues/305

**Comment by dmuelle** [comment] 2022-06-20 13:31
note release retention scheme for DockerHub in the slack thread: https://ibm-cloud.slack.com/archives/C31DW78RG/p1655127847023539. This should be documented on the new page

> Each release is published to Dockerhub, but only the longer-supported releases (ending in 3, 6, 9, and 12) are kept longer than 1 month when the next release goes live. So 22.0.0.5 will go away once 22.0.0.6 gets published, and since it ends in .6, that will stay when 22.0.0.7 gets published, which will be replaced in August when 22.0.0.8 is published

**Comment by NottyCode** [comment] 2022-08-24 19:33
@dmuelle What is the status of this? It isn't clear to me why the lack of a beta image in ICR would be a blocker for documenting what is currently in ICR.io, but the comment thread suggests that it is blocking progress on this.

**Comment by dmuelle** [comment] 2022-08-24 19:56
targeting to publish w/out mention of betas in 22.0.0.10

**Comment by dmuelle** [comment] 2022-09-26 15:35
The draft for this topic is now available for review:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/container-images.html

please let me know if any changes are needed, thanks

**Comment by dmuelle** [comment] 2022-09-26 16:22
Currently, this doc lists the available images, explains how to pull them from ICR, and details the current release + 2 most recent quarterly release maintenance strategy. It points out to the [Open Liberty container image GitHub documentation](https://github.com/OpenLiberty/ci.docker#readme) for more details. The GH docs contain the following sections that are not currently covered in OL Docs:
[Enterprise Functionality](https://github.com/OpenLiberty/ci.docker#enterprise-functionality)
[Security](https://github.com/OpenLiberty/ci.docker#security)
[OpenJ9 Shared Class Cache (SCC)](https://github.com/OpenLiberty/ci.docker#openj9-shared-class-cache-scc)
[Logging](https://github.com/OpenLiberty/ci.docker#logging)
[Session Caching](https://github.com/OpenLiberty/ci.docker#session-caching)
[Applying Interim Fixes](https://github.com/OpenLiberty/ci.docker#applying-interim-fixes)
Should we move this info into the OL docs or is it sufficient just to point to the GH doc?

**Comment by leochr** [comment] 2022-10-17 22:45
@dmuelle Thanks for the updates. Some comments:

- [x] `You can use Open Liberty container image tags to obtain a container image that meets your development needs.` 
Tag is optional. The following can be beneficial/informative instead: `You can use an Open Liberty container image to build an application image.`
- [x] After `One advantage of using ICR instead of Docker Hub is that ICR doesn’t impose rate limits on image pulls.` Add `Images can be pulled from ICR without authentication.`
- [x] `Current options are Open J9 and, for Java SE 8 only, the IBM SDK, Java Technology Edition.` It should be `OpenJ9`. Also state that these images currently include IBM Semeru (IBM Semeru with Eclipse OpenJ9 perhaps ?) 
- [x] `You can use container image tags in a Dockerfile or Containerfile to build an application image that adds a single application and its corresponding configuration.`. Suggest `You can use an Open Liberty container image in a Dockerfile or Containerfile to build an application image that adds a single application and its corresponding configuration.`
- [x] `It is available from ICR and Docker Hub and is rebuilt daily. ` - Remove `rebuilt daily` as it's no longer true since the move to new build system (OnePipeline)

**Comment by dmuelle** [comment] 2022-10-18 19:10
Thanks for reviewing @leochr - all comments have been addressed in the rebuilt draft:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/container-images.html

If any further changes are needed, just let me know. If not, you can add the `Technical reviewed` label to this issue to sign off and the doc will publish with the 22.0.0.11 release. Thanks!

**Comment by leochr** [comment] 2022-10-18 20:56
@dmuelle Thanks for the updates. Looks good to me.

**Comment by ramkumar-k-9286** [comment] 2022-10-19 10:22
Peer Review
---
One advantage of using ICR instead of Docker Hub is that ICR doesn’t impose rate limits on image pulls. 
-->
One advantage of using ICR instead of Docker Hub is that ICR **does not** impose rate limits on image pulls. 

---
Current options are IBM Semeru with Eclipse OpenJ9 and**,** for Java SE 8 only, the IBM SDK, Java Technology Edition.
-->
Acrolinx picking up the punctuation. Need to rephrase

Current options are IBM Semeru with Eclipse OpenJ9 and for Java SE 8 only, the IBM SDK, **and** Java Technology Edition.

---
beta: This tag provides the most recent beta release, which includes all the features and capabilities from the most recent release, plus new and updated features that are currently in development.
-->
beta: This tag provides the most recent beta release, **that** includes all the features and capabilities from the most recent release, plus new and updated features that are currently in development.

---
Set up your image template similar to the following example, which uses the `kernel-slim-java17-openj9-ubi` tag to build an image that uses the latest Open Liberty release with the OpenJ9 distribution of Java 17.
-->
Too long - Acrolinx
In the following example, which uses the `kernel-slim-java17-openj9-ubi` tag is used to build an image that uses the latest Open Liberty release with the OpenJ9 distribution of Java 17. Set up your similar image template.

---
For more information about the different arguments and environment variables you can specify to customize your application image, see the [Open Liberty container image GitHub documentation](https://github.com/OpenLiberty/ci.docker#readme).
-->
For more information about the different arguments and environment variables **that** you can specify to customize your application image, see the [Open Liberty container image GitHub documentation](https://github.com/OpenLiberty/ci.docker#readme).

---
Also noticed a lot of Java mentions within the document -> Do they need to be Jakarta by any chance?

**Comment by dmuelle** [comment] 2022-10-19 16:42
Thanks for reviewing @ramkumar-k-9286 , all suggestions implemented except

> One advantage of using ICR instead of Docker Hub is that ICR **does not** impose rate limits on image pulls.

Contractions are ok

---

> Current options are IBM Semeru with Eclipse OpenJ9 and**,** for Java SE 8 only, the IBM SDK, Java Technology Edition.

This is weird but it's a false positive from acrolinx. Only two items in the list so no serial comma is needed. The final comma is part of the product name.

---

> beta: This tag provides the most recent beta release, that includes all the features and capabilities from the most recent release, plus new and updated features that are currently in development.

This is a dependent clause, which should use "which" rather than "that"

---

> Set up your image template similar to the following example, which uses the kernel-slim-java17-openj9-ubi tag to build an image that uses the latest Open Liberty release with the OpenJ9 distribution of Java 17.

Fixed this by just removing "up"- no longer flagged by acrolinx.

---

> Also noticed a lot of Java mentions within the document -> Do they need to be Jakarta by any chance?

No, references to Java on this page pertain to Java SE, not Java EE, which we would update to Jakarta EE.

**Comment by dmuelle** [comment] 2022-10-21 17:19
updates are on vNext and will publish with 22.0.0.11- closing this issue.

**Comment by dmuelle** [comment] 2022-10-26 20:21
moving to "Deployment" section pending discussion of a Cloud section in an upcoming release

**Closed as completed** 2022-11-10 15:50 UTC
Labels: technical reviewed, peer reviewed
