### ISSUE TITLE
Section ordering is inconsistent between topics

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#149] opened 2019-03-19 14:10 UTC
https://openliberty.io/docs/ref/command/#server-commands.html

I believe we agreed that the 'Usage examples' section should be first. I'm just checking what the rest of the order should be but I think something like this: https://openliberty.io/docs/ref/command/#server-package.html

Not like this: https://openliberty.io/docs/ref/command/#server-create.html

**Comment by Charlotte-Holt** [comment] 2019-04-25 20:29
@lauracowen It looks like most of the server commands are organized in the order of:
- Usage
- Syntax
- Options
- See also 
- Exit codes
- Server process

Is this the order that we want to keep? If so, I'll go through and update the server commands so that their sections are all laid out in the same order. Also, I noticed that only some of the server commands have server process included. This may be because it just doesn't apply to some of them.

**Comment by lauracowen** [comment] 2019-04-26 09:56
I think this one is about right: https://draft-openlibertyio.mybluemix.net/docs/ref/command/#server-package.html

It may be that there aren't that many inconsistencies overall (eg maybe where topics start with the Syntax heading it's just because there wouldn't be any usage examples to include beyond what's shown in the Syntax section).

"Usage" should be "Usage examples" more consistently (some topics seem to use one and some use the other). Otherwise, I think the ordering in your comment above looks fine.

See what you work out about the exit codes and server process info in the other issue.

**Comment by Charlotte-Holt** [comment] 2019-05-03 13:19
Confirmed with @cbridgha that "Server process" **does** apply to all server commands, so I think if we're going to be including this on the server command page (rather than separating it and linking to it), then it should be included on all server command pages. Also, Chuck mentioned that a better name for "Server process" would be "Server process properties".

**Comment by Charlotte-Holt** [comment] 2019-05-17 20:39
@lauracowen I think this one is finished up. See https://draft-openlibertyio.mybluemix.net/docs/ref/command/ to review the topics on the draft site. They should all be in the same order now:
- Usage examples
- Syntax
- Options
- See also
- Exit codes

**Comment by Charlotte-Holt** [comment] 2019-06-06 18:02
Updated so that all server commands have consistent ordering: 

- https://openliberty.io/docs/ref/command/#server-create.html
- https://openliberty.io/docs/ref/command/#server-debug.html
- https://openliberty.io/docs/ref/command/#server-dump.html
- https://openliberty.io/docs/ref/command/#server-help.html
- https://openliberty.io/docs/ref/command/#server-javadump.html
- https://openliberty.io/docs/ref/command/#server-list.html
- https://openliberty.io/docs/ref/command/#server-package.html
- https://openliberty.io/docs/ref/command/#server-pause.html
- https://openliberty.io/docs/ref/command/#server-resume.html
- https://openliberty.io/docs/ref/command/#server-run.html
- https://openliberty.io/docs/ref/command/#server-start.html
- https://openliberty.io/docs/ref/command/#server-stop.html
- https://openliberty.io/docs/ref/command/#server-version.html

Closing this issue!

**Closed by Charlotte-Holt** 2019-06-06 18:02 UTC
Labels: doc bug
