### ISSUE TITLE
JAAS and Open Liberty

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#997] opened 2020-02-03 19:30 UTC
per discussion with Ajay Reddy- move JAAS info out of Authentication topic into new topic, include more detail from KC topics

https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_config_jaas_db_auth.html

https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_dev_jaas_custom_login_module.html

https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_dev_custom_idassertion.html

**Comment by Charlotte-Holt** [comment] 2020-12-08 15:46
Duplicate of #3359. Closing.

**Closed by Charlotte-Holt** 2020-12-08 15:46 UTC
Labels: concept
