### ISSUE TITLE
ID: Support SSO LTPA key rotation without requiring planned outage

### ISSUE THREAD

**Issue by utle** [OpenLiberty/docs#6805] opened 2023-08-02 15:06 UTC
Epic # 18499
UFO: LTPA Enhancements - part 1

**Comment by utle** [comment] 2023-08-02 15:06
https://github.com/OpenLiberty/open-liberty/issues/18499

**Comment by dmuelle** [comment] 2023-08-16 20:08
duplicate of #6821 , closing this issue

**Closed as completed by dmuelle** 2023-08-16 20:08 UTC
Labels: 23.0.0.9
