### ISSUE TITLE
Add a little info about convenience features to the features overview topic

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#3343] opened 2020-12-02 16:50 UTC
https://openliberty.io/docs/latest/reference/feature/feature-overview.html

The "Using features" section of the feature overview topic talks about how to enable specific features in the server.xml. It could also mention (a sentence or two) that there are some "convenience features" that mean you can enable a whole set of features at once. You'll need to find out what they are (Chuck might be able to help there) but there's one for each version of Java/Jakarta EE (full profile and web profile flavours), one for each version of MicroProfile. 

There might be one for all GA features but I'm not sure - there's definitely a package for downloading/installing them in your liberty but not sure if there's a convenience feature to enable them all at once in a single server/app - you can't enable certain combinations anyway, as described further down in the topic already.

**Comment by ramkumar-k-9286** [comment] 2021-08-10 18:36
@cbridgha 

Hi, 
We have a docs issue to add some information about the Open Liberty convenience features to the [features overview](https://www.openliberty.io/docs/21.0.0.8/reference/feature/feature-overview.html) topic.
I know we have convenience features for MicroProfile and several for Java EE. Are there any others? And is the term "convenience feature" the best thing to call these features?

Regards,
Ramkumar

CC @dmuelle

**Comment by dmuelle** [comment] 2021-08-10 18:57
Here are the ones I known of, not sure if there are others:

- [Enterprise JavaBeans](https://www.openliberty.io/docs/latest/reference/feature/ejb-3.2.html)
- [MicroProfile](https://www.openliberty.io/docs/latest/reference/feature/microProfile-4.0.html)
- [Java EE Full Platform](https://www.openliberty.io/docs/latest/reference/feature/javaee-8.0.html)
- [Java EE Web Profile](https://www.openliberty.io/docs/latest8/reference/feature/webProfile-8.0.html)

I do see "convenience feature" used in a few places in Liberty IBM docs, so there is a precedent

**Comment by ramkumar-k-9286** [comment] 2021-09-23 13:52
After discussions with Chuck, Jared & Tracy:

Shortlist of the Convenience features are:
Jakarta EE Platform 9.1
Jakarta EE Web Profile 9.1
Jakarta EE Application Client 9.1
ejb-3.2 and the Jakarta version, (They provide no unique function, only enable other features.)
enterpriseBeans-4.0 (They provide no unique function, only enable other features.)

These will be included in the document https://openliberty.io/docs/latest/reference/feature/feature-overview.html

**Comment by dmuelle** [comment] 2021-09-23 14:43
since the Jakarta features won't be available until Open Liberty supports EE 9.1, we should not publish this doc until then. 9.1 is currently targeted for 21.0.0.11, but might move out to 21.0.0.12. The work can continue on draft, just need to wait to push anything to staging.

**Comment by ramkumar-k-9286** [comment] 2021-09-28 11:23
@dmuelle 
i was doing some research on wikipedia regarding EJB. https://en.wikipedia.org/wiki/Jakarta_Enterprise_Beans
they are calling it Jakarta Enterprise beans. Just a bit confused on this.

so from our list:
ejb-3.2 and the Jakarta version, (They provide no unique function, only enable other features.)
enterpriseBeans-4.0 (They provide no unique function, only enable other features.)

should these be also referred as Jakarta Enterprise Beans as we are planning this for 9.1 ?

**Comment by dmuelle** [comment] 2021-09-30 14:26
Jakarta EE 9 moved to 21.0.0.12- can continue working the draft for this issue but do not publish until 21.0.0.12

**Comment by ramkumar-k-9286** [comment] 2021-10-11 11:34
Communication with all the SME are documented below: **(FOR REFERENCE)**

Ramkumar K  9:29 PM
We have a docs issue to add some information about the Open Liberty convenience features to the features overview topic.
I know we have convenience features for MicroProfile and several for Java EE. 
Are there any others? And is the term "convenience feature" the best thing to call these features?
Here are the ones I know of, not sure if there are others:

**Enterprise JavaBeans
MicroProfile
Java EE Full Platform
Java EE Web Profile**

Chuck Bridgham  10:15 PM
Hi - Yes - So the list you provided - I wouldn’t group EJB as a convenience feature.   
This brings in multiple dependent EJB features, and rarely someone would pick and choose some of these.    
The other three you mentioned are indeed “convenience” for bringing in appropriate versions of each subspec in the Java EE or Jakarta EE version.  
The same goes with Micro-profile. I found this existing link explaining the Java EE 8 features.
https://www.ibm.com/docs/en/was-liberty/base?topic=overview-jakarta-java-ee-8-in-liberty

@jared is also a good source because he is managing the latest Jakarta EE 9.1 rollout for Liberty - so he would know any latest details for these versions.
The special packages you mentioned do use these convenience features as a default feature.

David Mueller  10:21 PM
Thanks Chuck- we'll check with Jared as well. 
Looks like we were missing javaeeClient . And we wont include EJB.
But is Java EE Managed Bean considered a convenience feature?

Chuck Bridgham  10:26 PM
yes thank you clients for each version.
For EJB and MDB - Check with @tkb - and see what he thinks it should be called. 
still not sure if it should be grouped with these umbrella spec features

David Mueller  10:27 PM
ok thanks will do
one last question! and this might be for Jared- 
but do you know if there are plans to update the convenience features to be Jakarta EE.. rather than Java?

Chuck Bridgham  10:30 PM
yes we have been releasing those in our beta drivers for months.
GA may be in Oct/Nov?  def ask Jared that

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Ramkumar K  11:34 PM
Hi Tracy, I’m Ramkumar with the ID team.
Chuck suggested that we check this with you.
Would you consider Enterprise Java Bean as a convenience feature  feature for OL ?

Tracy Burroughs  11:55 PM
Yes, both ejb-3.2 and the Jakarta version, enterpriseBeans-4.0 are convenience features.  
They provide no unique function, only enable other features.

Ramkumar K  1:30 AM
Tracy. Hi. Just wanted to clarify something with you.
ejb-3.2 text name is enterpriseBeans-4.0  right?

Tracy Burroughs  1:31 AM
no, those are two different features

Ramkumar K  1:33 AM
in that case what is the text name of ejb-3.2 ?

Tracy Burroughs  1:34 AM
ejb-3.2             -> Enterprise JavaBeans 3.2
enterpriseBeans-4.0 -> Jakarta Enterprise Beans 4.0
The first is from Java EE, the second is a new version of the spec for Jakarta EE.

Ramkumar K  1:35 AM
ok. just got confused with the usage. thanks for the clarification

Tracy Burroughs  1:43 AM
So, depending on what you are trying to explain about convenience features, this is how they relate:

webProfile-8.0
   - ejbLite-3.2

webProfile-9.1
   - enterpriseBeans-4.0

javaee-8.0/jakartaee-8.0
   - ejb-3.2
      - ejbLite-3.2
      - ejbHome-3.2
      - ejbRemote-3.2
      - ejbPersistentTimer-3.2
      - mdb-3.2

jakartaee-9.1
   - enterpriseBeans-4.0
      - enterpriseBeansLite-4.0
      - enterpriseBeansHome-4.0
      - enterpriseBeansRemoe-4.0
      - enterpriseBeansPersistentTimer-4.0
      - mdb-4.0
      
The webProfile and javaee/jakartaee convenience features also contain other features.... but this shows the EJB related features and how they are included in those.

ejb-3.2 and enterpriseBeans-4.0 are also convenience features, which are a subset of the javaee/jakartaee ones.... and they contain all of the EJB related ones.

Ramkumar K  1:47 AM
ok. Thanks for the explanation

Tracy Burroughs  1:48 AM
it is a bit confusing because EJB was copyrighted by Oracle, so shouldn't be used for the Jakarta spec levels, thus the new feature names switched from ejb to enterpriseBeans. (edited) 

Ramkumar K  1:49 AM
ya i was confused because i thought we would not be using ‘JAVA’
while documenting this

Tracy Burroughs  1:52 AM
correct, EJB stands for Enterprise JavaBeans and is acceptable to use when describing ejb-3.2, as that belongs to the Java EE specification.  
However, starting with the Jakarta spec levels, we should not use Java, so the new version of Enterprise JavaBeans became Jakarta Enterprise Beans , and the features became enterpriseBeans (edited) 

Ramkumar K  1:53 AM
Thanks Tracy. for taking the effort to explain this
i will make the updates and share the draft links to confirm that the update made is based on what u have suggested here

Tracy Burroughs  1:54 AM
np, any doc that can help clarify this is going to help our customers through this transition

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

David Mueller  12:07 AM
Hi Jared, We have a docs issue to add some information about the Open Liberty convenience features to the features overview topic. 
Chuck suggested we check with you on the Java/Jakarta convenience features. I believe there are three:
Java EE Application Client
Java EE Full Platform
Java EE Web Profile
I believe the names will be changing Java-->Jakarta, most likely in 21.0.0.11? If so we will most likely not publish the update until after that change. 
Are these the only convenience features associated with Jakarta EE?

Jared Anderson  12:09 AM
Yes those are the convenience features
Will you have a separate section for 9?
Note there is already Jakarta EE 8 (edited) 

David Mueller  12:12 AM
Will be both Java and Jakarta features? Or will the Java EE features go away with 9

Jared Anderson  12:12 AM
Java EE goes away with 9
It will just be Jakarta EE Platform 9.1, Jakarta EE Web Profile 9.1 and Jakarta EE Application Client 9.1

David Mueller  12:14 AM
since this particular issue is just to explain what the convenience features are, (MP and Jakarta), 
would probably just include a statement that prior to 21.0.0.11, Jakarta EE features were Java EE

Jared Anderson  12:16 AM
We made a jakartaee-8.0 like I stated.  It is just a duplicate of javaee-8.0.
This was so customers could do jakartaee-8.0 instead of javaee-8.0 to say they were using Jakarta EE 8 instead of Java EE 8 even though for us they were identical.

David Mueller  12:19 AM
ok- so then jakartaee-9.0 will replace both javaee-8.0 and jakartaee-8.0?

Jared Anderson  12:22 AM
jakartaee-9.1
there is no longer a jakartaee-9.0
We made the 9.1 do an aka to 9.0 so if a customer does specify 9.0, it will give them the message to use 9.1.

David Mueller  12:25 AM
ok good to know for upcoming edits- I was referencing the table in this blog post but its out of date.
Enabling Jakarta EE 9 for development and test by using the Eclipse Transformer

Jared Anderson  12:26 AM
Yeah that blog was made prior to 9.1 existing.

**Comment by ramkumar-k-9286** [comment] 2021-11-11 11:54
@dmuelle

All the review comments specified above have been incorporated.

Proceeding to Merge the PR. Will share the draft link for review.

Link to the draft version of the document:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.12/reference/feature/feature-overview.html

Regards,
Ramkumar

**Comment by dmuelle** [comment] 2021-11-11 15:05
- the definition list is not rendering properly. When you use a defintion list, you don't need `*` at the beginning of each line.
- we forgot to mention the [MicroProfile](https://www.openliberty.io/docs/latest/reference/feature/microProfile-4.0.html) convenience feature. I think you can add it after the EE9 features, before the EJB feature
- the enterpriseBeans convenience feature--->=the Enterprise Beans convenience feature
- otherwise looks good, but nI'll review agin once those changes go in

**Comment by ramkumar-k-9286** [comment] 2021-11-12 06:23
Hi David @dmuelle

The review comments specified above were incorporated. Proceeding to Merge the PR. 

Link to the draft version of the document:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.12/reference/feature/feature-overview.html

Regards,
Ramkumar

**Comment by dmuelle** [comment] 2021-11-12 14:37
Looking at this, I think the definition list is overkill and looks strange with the other features- sorry about that.

I think we should reformat the EE9 features list as a normal bulleted list, like the two other features below it. For example

The following convenience features are available for the for Jakarta EE platform.
- The feature:jakartaee[display=Jakarta EE Platform] feature enables all features that are associated with the Jakarta EE platform.
- The feature:webProfile[display=Jakarta EE Web Profile] feature enables only features that are associated...etc

Then we can add a statement about the Java EE features, but no need to explain them again

" Similar convenience features are available for the  Java EE platform.
- feature:javaee-8.0[display Java EE Full Platform]
- feature:webProfile-8.0[display=Java EE Web Profile]
- feature:javaeeClient-8.0[display=Java EE Application Client]

Open Liberty provides two additional convenience features....."

then the rest as you already have it. 


Note in the current draft need to fix: 

- a convenience features enables ---> a convenience feature enables 
-  additional convinience--->more convenience (acrolinx dings "additional" and convenience is misspelled)

**Comment by ramkumar-k-9286** [comment] 2021-11-15 10:35
Hi David @dmuelle

Comments specified above were incorporated. Proceeding to Merge the PR.

Link to the draft version of the document:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.12/reference/feature/feature-overview.html

I was not sure about adding the Java related comments, wanted to discuss this with you on Friday. 

Regards,
Ramkumar

**Comment by dmuelle** [comment] 2021-11-15 15:15
Changes look good- we can dsicuss adding the Java features, I think it will be helpful for users to understand how we support java vs jakarta platforms.

The only additional change I'd recommend- I think we should consistently use the term "support" to describe the relationship between the features and the platforms. You've aldready used it for MicroProfile and EJB, just need to edit the Jakarta statements, like

`Jakarta EE Platform feature enables all the features that are part of the Jakarta EE Platform.`
--->
`Jakarta EE Platform feature enables all the features that support the Jakarta EE Platform.`

`The Jakarta EE Platform feature enables all features that are associated with the Jakarta EE platform.`
--->
`The Jakarta EE Platform feature enables all features that support the Jakarta EE platform.`

and so on..

**Comment by ramkumar-k-9286** [comment] 2021-11-15 19:45
@dmuelle

Link to the draft version of the document:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.12/reference/feature/feature-overview.html

Regards,
Ramkumar

**Comment by dmuelle** [comment] 2021-11-15 20:27
LGTM- ready for technical review

**Comment by ramkumar-k-9286** [comment] 2021-11-15 20:59
Hi Chuck @cbridgha

Please find below the draft links for the requested changes on convenience features:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.12/reference/feature/feature-overview.html

Please review the same. If the section has turned out as expected, please add the `Technical reviewed` label.

In case changes are needed please add your comments to the issue.

Regards,
Ramkumar

CC @dmuelle

**Comment by ramkumar-k-9286** [comment] 2021-11-23 17:21
**Conversation with Chuck (for reference)**
# 
Ramkumar K  [10:33 PM]
Hi Chuck, Michal/Steven is working on the webprofile features.
Is there anything else with the Convenience features update that would need correction?

Chuck Bridgham  [10:40 PM]
Looks good to me

Ramkumar K  [10:40 PM]
ok. Thanks
# 

Proceeding to add the `Technical Reviewed` label.

CC @dmuelle

Regards,
Ramkumar

**Comment by dmuelle** [comment] 2021-11-23 22:07
LGTM- adding peer review label

**Closed as completed** 2021-12-03 01:29 UTC
Labels: technical reviewed, peer reviewed
