### ISSUE TITLE
New updated Document for Request timing: Diagnosing slow requests on WAS Liberty

### ISSUE THREAD

**Issue by tomjenningss** [OpenLiberty/docs#1134] opened 2020-02-25 11:05 UTC
As WASdev is being closed down it has been decided that a new document should be created for Diagnosing slow requests on WAS Liberty, but in the context of Open Liberty and on the Open Liberty docs.
The old post is being redirected to the Open Liberty blog post 'https://openliberty.io/blog/2019/11/08/diagnose-slow-requests-easily-190011.html'.

**Comment by lauracowen** [comment] 2020-03-24 14:14
<p class="wasdev-excerpt">Request timing is a new Liberty feature which automatically identifies slow and hung requests and provides detailed information to help you find the root cause. This article explains how to use the request timing capability in WAS Liberty to detect and diagnose problems related to slowness of a request.</p>

By <a href="mailto:dbourne@ca.ibm.com">Don Bourne</a> and <a href="mailto:venu.madhav@in.ibm.com">Venumadhav Vanagondi</a>

Until now, diagnosing the cause of slow web requests in application servers has often been a challenging endeavor.  The request timing feature in <a href="/wasdev/downloads/liberty-profile-using-non-eclipse-environments/">WAS Liberty 8.5.5.6</a> makes it easier.

Traditional approaches for finding problems related to slowness of a request involve using a variety of tools in conjunction with trace and log information. Some examples are:

<ul>
    <li>Slow spots in the code are identified by profiling. Profiling is good at showing which methods are slow, but doesn't generally show contextual details such as servlet parameters or SQL statements that are often needed. Not everyone is willing to run profilers on their production systems.</li>
    <li>Database query slowness requires identifying slow SQL queries. This can be done by enabling trace on the application server. Tracing causes overhead and reviewing trace output is not an easy task.</li>
    <li>Monitoring tools are used to detect bottlenecks in resource pools, such as the thread pool, JDBC connection pool etc. Monitoring can help you find certain problems, but won't help you unless the root cause ties closely to a tracked metric.</li>
</ul>

The other key problem with the above approaches is that they generally require enabling some form of diagnostics and recreating problem scenarios – which is not always possible and which prolongs problem diagnosis.

<em>Request timing</em> is a new Liberty feature which automatically identifies slow and hung requests and provides detailed information to help you find the root cause.  Request timing can run all the time – enabling slow and hung requests to be documented when they occur, without the need for problem recreation to collect more data.

<h3>Slow request detection</h3>

Request timing includes slow request detection.  This capability is useful for identifying requests that have run for longer than a slow request threshold that you can configure. For each request that takes too long to complete, request timing prints a warning message along with the details captured for the request into the log file. A maximum of three messages are printed per slow request after which request timing stops monitoring the request.

The information captured for a request includes:

<ul>
    <li>The current stack for the thread that the request is using.</li>
    <li>A dump of the tree of events that happened during the request</li>
</ul>

<h3>Hung request detection</h3>

Request timing also includes hung request detection.  Hung request detection works similarly to slow request detection. A request is considered to be hung when it has run for longer than a hung request threshold that you can configure.  For a hung request, apart from printing a warning message along with the relevant details, request timing initiates Java cores. Three Java cores are generated for a hung request, each a minute apart.

<h2>How does request timing work?</h2>

Request timing is built on top of a new bytecode injected request probe framework. The request probe framework works by adding probes at predefined locations in Liberty components.  Instrumented components generate events at these predefined probe points. The request probe framework tracks each request throughout its life in the Liberty server.  The framework assigns each request a unique request ID and stores information about the events that happen throughout the request. Events are stored in a event tree, which is built as the request progresses.

Every event has the following attributes

<ul>
    <li>Event type, identifies the kind of an event and provides information about the event source.</li>
    <li>Context information, describes an instance of an event and provides information relevant to the event type. Depending on the event type this information will vary.</li>
    <li>Duration, captures the time taken by the event.</li>
</ul>

At the time of writing this article, there are event types for servlets, sessions and database connectivity. Please refer to the Liberty knowledge center for the latest and full list of supported event types.

<h2>Configuring slow and hung request detection</h2>

Enable request timing, including both slow and hung request detection, by adding the <code>requestTiming-1.0</code> feature to the feature manager in the Liberty <code>server.xml</code> file as follows:

[code lang="xml"]
    <featureManager</>
        <feature/>requestTiming-1.0</feature>
    </featureManager>
  [/code]

The default behavior for request timing is to consider any requests that take at least 10 seconds to be slow, and to consider any requests that take at least 10 minutes to be hanging.  The request timing feature provides optional configuration options as follows:

[code lang="xml"]
    <requestTiming
     includeContextInfo="true"
     slowRequestThreshold="10s"
     hungRequestThreshold="10m"
     sampleRate="1"
    />
  [/code]

Where:

<ul>
<li><code>slowRequestThreshold</code> is the duration of time that a request can run before being considered slow.  Default is 10 seconds.  Set to <code>0</code> to disable slow request checking.</li>
<li><code>hungRequestThreshold</code> is the duration of time that a request can run before being considered hung.  Default is 10 minutes.  Set to <code>0</code> to disable hung request checking.</li>
<li><code>sampleRate</code> is the rate at which the sampling should happen for the slow request tracking.  Default is every request (1).</li>
<li><code>includeContextInfo</code> indicates if the context information details are included in the log output.  Default is <code>true</code>.</li>
</ul>

How you configure the request timing feature depends on your use case.

<h3>Configuring request timing on production servers</h3>

For a production server, use request timing to watch for slow or hung requests that may warrant further investigation.  A good time to tune request timing threshold values is during load testing.  As with any pre-production performance testing, you should try to use a workload representative of what you are expecting to see in production, and should run on hardware that is as similar as possible to the target environment.

While the workload driving tool runs, try different values for the <code>slowRequestThreshold</code> setting to find one that you like.  Setting the value too low isn't helpful -- avoid picking a value so low that you wouldn't care to investigate the resultant slow request warnings.  For example, if you don't think you'd care to investigate any requests that complete within 2 seconds you should probably pick a number bigger than 2 seconds for your setting.

For hung request detection, keep in mind that any requests that last longer than the <code>hungRequestThreshold</code> will trigger 3 javacores to be created. Pick a number that isn't too small or the system will create unnecessary javacores. Something in the range of 1m-10m is probably reasonable.

<h3>Configuring request timing in development and test environments</h3>

For development and test environments, use request timing to see all requests that are slow. Set the value of <code>slowRequestThreshold</code> to a fairly low value. This will give you a feel for which of your servlets take the longest to run, and will give you a chance to investigate the slow request reports to see if there's anything going on in your application that you weren't expecting.

Note that setting the <code>slowRequestThreshold</code> to <code>0</code> disables slow request checking, and setting the <code>slowRequestThreshold</code> to a small value increases the frequency with which the server will scan for slow requests. Consider setting the <code>slowRequestThreshold</code> to something in the range of 300ms – 500ms.

You will normally leave the <code>sampleRate</code> set to <code>1</code> and the <code>includeContextInfo</code> set to <code>true</code> unless you see a performance issue when running with slow request timing enabled. Increasing the <code>sampleRate</code> makes the slow request detection skip requests; for example setting it to <code>100</code> would make the server only check 1 out of every 100 requests for slowness.

Changing <code>includeContextInfo</code> to <code>false</code> causes the runtime to not get the context for events, which saves some CPU, but greatly reduces the value of the event trees. Note that hung request detection applies to all requests regardless of the <code>sampleRate</code> setting (this is so that you'll never miss a hung request, even one that happens due to a sporadic condition).

<h2>What output to expect</h2>

When a request in the server has been running for longer than the <code>slowRequestThreshold</code>, you will get a slow request timing message written to your <code>messages.log</code> file:

<pre style="border: 1px solid #ccc">
[6/8/15 15:12:35:101 IST] 00000040 com.ibm.ws.request.timing.manager.SlowRequestManager         W TRAS0112W: Request AABU1rUO7kq_AAAAAAAAAAA has been running on thread 0000003f for at least 2009.020ms. The following stack trace shows what this thread is currently running.

     at org.apache.derby.impl.sql.execute.ScalarAggregateResultSet.getNextRowCore(Unknown Source)
     at org.apache.derby.impl.sql.execute.ProjectRestrictResultSet.getNextRowCore(Unknown Source)
     at org.apache.derby.impl.sql.execute.BasicNoPutResultSetImpl.getNextRow(Unknown Source)
     at org.apache.derby.impl.jdbc.EmbedResultSet.movePosition(Unknown Source)
     at org.apache.derby.impl.jdbc.EmbedResultSet.next(Unknown Source)
     at com.ibm.ws.rsadapter.jdbc.WSJdbcResultSet.next(WSJdbcResultSet.java:2356)
     at com.ibm.websphere.samples.trade.direct.TradeDirect.resetTrade(TradeDirect.java:1884)
     at com.ibm.websphere.samples.trade.web.TradeConfigServlet.doResetTrade(TradeConfigServlet.java:65)
     at com.ibm.websphere.samples.trade.web.TradeConfigServlet.service(TradeConfigServlet.java:348)
     at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
     at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1285)
     ....
     at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:955)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1177)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
     at java.lang.Thread.run(Thread.java:857)

The following table shows the events that have run during this request.

Duration     Operation
2011.614ms + websphere.servlet.service | TradeWeb | TradeConfigServlet?action=resetTrade
  56.499ms       websphere.datasource.psExecuteUpdate | jdbc/TradeDataSource | delete from holdingejb where holdingejb.account ..
   0.411ms       websphere.datasource.psExecuteUpdate | jdbc/TradeDataSource | delete from accountprofileejb where userid like ..
   0.365ms       websphere.datasource.psExecuteQuery | jdbc/TradeDataSource | select count(symbol) as "tradeStockCount" from ..
  34.901ms       websphere.datasource.psExecuteUpdate | jdbc/TradeDataSource | update accountejb set logoutCount=0 ..
</pre>

When a request in the server has been running for longer than the <code>hungRequestThreshold</code>, you will get hung request timing message written to your <code>messages.log</code> file:

<pre style="border: 1px solid #ccc">
[6/9/15 14:50:19:937 IST] 00000034 com.ibm.ws.request.timing.manager.HungRequestManager         W TRAS0114W: Request AABoLUq4OHj_AAAAAAAAAAA has been running on thread 00000038 for at least 2001.732ms. The following table shows the events that have run during this request.

Duration     Operation
2002.355ms + websphere.servlet.service | TradeWeb | TradeConfigServlet?action=resetTrade
  22.141ms       websphere.datasource.psExecuteUpdate | jdbc/TradeDataSource | delete from holdingejb where holdingejb.account ..
   0.433ms       websphere.datasource.psExecuteUpdate | jdbc/TradeDataSource | delete from accountprofileejb where userid like ..
   0.306ms       websphere.datasource.psExecuteQuery | jdbc/TradeDataSource | select count(symbol) as "tradeStockCount" from ..
  34.526ms       websphere.datasource.psExecuteUpdate | jdbc/TradeDataSource | update accountejb set logoutCount=0 ..

[6/9/15 14:50:19:943 IST] 00000034 com.ibm.ws.kernel.launch.internal.FrameworkManager           A CWWKE0067I: Java dump request received.
[6/9/15 14:50:20:684 IST] 00000034 com.ibm.ws.kernel.launch.internal.FrameworkManager           A CWWKE0068I: Java dump created: C:WorkIMD2015build.imagewlpusrserverstestServerjavacore.20150609.145019.6116.0001.txt
[6/9/15 14:51:19:943 IST] 00000046 com.ibm.ws.kernel.launch.internal.FrameworkManager           A CWWKE0067I: Java dump request received.
[6/9/15 14:51:21:083 IST] 00000046 com.ibm.ws.kernel.launch.internal.FrameworkManager           A CWWKE0068I: Java dump created: C:WorkIMD2015build.imagewlpusrserverstestServerjavacore.20150609.145119.6116.0002.txt
[6/9/15 14:52:19:945 IST] 0000004b com.ibm.ws.kernel.launch.internal.FrameworkManager           A CWWKE0067I: Java dump request received.
[6/9/15 14:52:20:601 IST] 0000004b com.ibm.ws.kernel.launch.internal.FrameworkManager           A CWWKE0068I: Java dump created: C:WorkIMD2015build.imagewlpusrserverstestServerjavacore.20150609.145219.6116.0003.txt

</pre>

When at least one request is determined to be hung, a set of 3 javacores will be initiated. No further javacores will be triggered by the request timing feature until the first set of javacores completes, and not until the list of hung requests changes from what triggered the previous javacores

<h2>Acting on slow request warnings</h2>

Garbage collection or momentary bursts of traffic to your site can be responsible for occasional slow requests, so you may not want to investigate a particular slow request warning unless the same events have previously caused other slow requests. When you see the same events repeatedly triggering slow request warnings you will likely want to find and address the cause.

The slow request detection warning message provides valuable info to help you diagnose why the request is still in progress:

<ul>
    <li>The start of the message tells you the request ID (for example, `AABU1rUO7kq_AAAAAAAAAAA`). This is helpful as any log or trace entries for the same request will be tagged with this same request ID. To see the request ID in the logs and trace you'll need to be using binary logging, which is able to show log records with their extensions.
For example, `binaryLog view servername --format=advanced`</li>
    <li>The thread ID listed in the message tells you which thread the request is running on (for example, `0000003f`). This is another way to see log or trace entries for the same request as the thread ID is part of each log and trace entry.</li>
    <li>The duration of the request, up until the moment the slow request detection decided to report on it, is listed (for example, `2009.020ms`). This is useful to note as the slow request detection message prints up to 3 times for each slow request -- at 1x, 2x, and 3x the `slowRequestThreshold`.</li>
    <li>The stack trace shows you the specific line of code being executed and the call stack of the thread the slow request is running on. For slower requests that may have up to 3 reports you can compare the stack traces from each report to see if the same method is still executing (indicative of a very slow or very frequently called method) or to check if there are any repeating sets of lines in the call stack (indicative of a recursive loop).</li>
    <li>The table of events shows how long each operation (event) within the request has taken to run. The duration of each event is shown in the duration column, and the details of the event are shown in the `Operation` column. A plus sign (+) is shown between the duration and operation columns for events that had not completed at the time the report was generated.</li>
</ul>

Take a look at the table of events to see where the time has been spent in the request.  There are many different scenarios you may encounter:

<ul>
    <li>You may see a large number of events, such as JDBC events.  If you developed the app, you can decide if all of the SQL statements are necessary.  If you're not the developer, you may want to discuss the report with the developer.</li>
    <li>You may see one or more very long JDBC events.  In some cases the queries may be able to be optimized, or new indices can be created in the database to reduce the time it takes to perform those queries.</li>
    <li>You may see long events that are not related to JDBC -- for example long servlet events.  While an exhaustive coverage of how to diagnose performance slowdowns is beyond the scope of this article, if there are no child events that indicate where the time was spent you may want to:
<ol>
    <li>Use system monitoring tools, such as `vmstat` and `iostat`, to check CPU and I/O levels. If your whole system is out of resources everything will be slow and you will likely be seeing a lot of slow request warnings.</li>
    <li>Look at the stack trace in the slow request warning message to get clues about what is slow.  Comparing the stack trace of the 1st, 2nd, and 3rd slow request messages (if there are multiple messages) will also help you see what the cause of the slowness is in cases where that event has not yet finished (as would be indicated by a plus sign).</li>
    <li>Monitor your system to check for connection wait time or a lack of threads in your thread pool</li>
    <li>Use a profiler, such as the *IBM Monitoring and Diagnostic Tools - Health Center* tool (available as a tool add-on to IBM Support Assistant), to see which specific methods the time is being spent in.</li>
</ol>
</li>
</ul>

<h2>Acting on hung request warnings</h2>

There are a number of reasons a request may hang:

<ol>
    <li>Long wait - When one thread (T1) spends a long time executing code while holding a lock (L1), causing all other threads (T2...Tn) that want to access the same code to have to wait. Often T1 is stuck waiting for availability of some resource, such as a connection from a connection pool.</li>
    <li>Deadlock - When a thread (T1) holds a lock (L1), and another thread (T2) holds another lock (L2), and where T1 is waiting for ownership of L2 while T2 is waiting for ownership of L1. This is commonly referred to as a deadlock.</li>
    <li>Loop - When an improperly coded method executes code in a loop that never ends.</li>
    <li>Infinite recursion - When an improperly coded method calls back to itself or to another method that eventually results in reaching the same point in the code, causing infinite recursion.</li>
</ol>

If you have multiple hung request messages for the same request you can compare the event trees to see if new events are being executed or not.  If new events are executing then you can rule out long waits and deadlocks as the problem.  In these cases you may be able to tell from the growing list of events what's causing the request to not reach completion.

If the event trees do not grow between warning messages, you may have a long wait or deadlock.  The easiest way to diagnose those kinds of problems is to analyze the javacore files that the request timing feature collects when hangs are detected.  The <em>IBM Thread and Monitor Dump Analyzer for Java</em> tool (also available as a tool add-on to IBM Support Assistant) can help with this analysis.

<h2>Conclusion</h2>

The new request timing feature in WAS Liberty can help you save time detecting and diagnosing the cause of slow and hanging requests.  Give it a try and let us know what you think!

<h2>Useful Links</h2>

<a href="http://www.ibm.com/developerworks/java/jdk/tools/healthcenter/" target="_blank">IBM Monitoring and Diagnostic Tools - Health Center</a>

<a href="https://www.ibm.com/developerworks/community/groups/service/html/communityview?communityUuid=2245aa39-fa5c-4475-b891-14c205f7333c" target="_blank">IBM Thread and Monitor Dump Analyzer for Java</a>

<a href="http://www.ibm.com/software/support/isa" target="_blank">IBM Support Assistant</a><ins datetime="2015-06-10T07:49:57+00:00"></ins>

**Comment by lauracowen** [comment] 2020-03-24 14:16
When published, create a PR to update the link in the [OL release blog post](https://openliberty.io/blog/2019/11/08/diagnose-slow-requests-easily-190011.html) to the old WASdev.net article so it points to the new doc topic instead.

**Comment by tomjenningss** [comment] 2020-03-25 08:30
Thank you @lauracowen.

**Comment by lauracowen** [comment] 2020-03-25 09:31
We’ll need to make some updates (i’ll stick all this in the issue too):
- Start by double-checking with Don that it’s fine with just minor updates to go on OL.io (that there’s nothing significant changed). Also check that it works in the context of containers and cloud or whether there needs to be an extra sentence here or there to situate it in the cloud context.
- remove mentions of it being a “new” feature
- remove mentions of WAS/WebSphere
- I can’t remember what the changes were in the 19.0.0.11 but (after committing what’s done so far, so we can compare the subsequent changes) if you can make sense of what’s changed in 19.0.0.11, identify what in this blog post might need updating. Also talk to Don about it to double-check.
- Some of the IBM links at the end should be removed - only keep things that are free and available to anyone to use (not the support assistant; maybe one or both of the other two tools, not sure).
- Get Don to review it to make sure it’s all still fine and nothing else has changed.

**Comment by tomjenningss** [comment] 2020-03-25 16:08
@lauracowen When do you want this to be ready for? I have created the document in docs drafts branch

**Closed** 2020-03-31 11:50 UTC
