### ISSUE TITLE
Clarify when to use featureUtility installFeature vs featureUtility installServerFeatures

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#6826] opened 2023-08-18 15:50 UTC
**Please describe the problem you are having with the documentation. Is information missing, inaccurate, or unclear? Tell us about the context where you encountered the problem so we can understand how to address it.**
See discussion here: https://github.com/OpenLiberty/blogs/pull/3264/files#r1298478785 regarding update to featureUtility installFeature and recommendation of using the other command anyway.

**Comment by dmuelle** [comment] 2023-08-18 15:56
duplicate of #6827

**Closed as completed by dmuelle** 2023-08-18 15:56 UTC
