### ISSUE TITLE
Slow and hung request detection

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#1127] opened 2020-02-24 15:18 UTC
This is a new concept topic for slow and hung request detection. The information in https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_requesttiming.html is all relevant. 

**Scenario 2**: Ops users with containers deployed to Kubernetes/OpenShift
**SME**: Don Bourne

**Comment by lauracowen** [comment] 2020-03-27 09:36
https://draft-openlibertyio.mybluemix.net/docs/ref/general/#requestTiming.html

**Comment by lauracowen** [comment] 2020-03-31 17:20
Pasting my feedback from slack in here for the record:

I did take a quick look at your request timing topic because, by coincidence, I happened to talk to Don about that this afternoon. We have an old article on WASdev.net about request timing: https://developer.ibm.com/wasdev/docs/request-timing-diagnosing-slow-requests-liberty/. Apparently it’s out-of-date (it’s 5 years old) but he said that if you combine the KC topic that you’re working from with the content/info from this WASdev.net article, you should get a nice intro to request timing in OL.

He mentioned that you’d already talked to him about your topic so I don’t know where you’re up to with that. He said that the info in the KC topic is pretty good and should mostly be included in your OL doc topic. Then see what you can do about integrating the WASdev.net article into that (I’m not sure if it’s extra sections or just extra explanation of stuff you’ve already covered in less detail).

Then when you’ve done that, get in touch with him to ask what more up-to-date material should be added. Actually, you might be able to pre-empt him a little because we have some of it in a release blog post here: https://openliberty.io/blog/2019/11/08/diagnose-slow-requests-easily-190011.html#dsr

I assume you've not worked on this topic yet so I'll move it back to In Progress (but change that if you have).

**Comment by donbourne** [comment] 2020-06-17 17:56
Reviewed draft at https://draft-openlibertyio.mybluemix.net/docs/ref/general/#requestTiming.html -- looks good!

**Comment by lauracowen** [comment] 2020-06-18 12:42
In general, this looks good. Thanks, both.

- Give the feature its proper name each time you mention it (ie " Request Timing feature"), instead of "`requestTiming` feature".
- Remove the 'Configure...' section. This info is in the feature topic. Instead, in the paragraphs above about slow requests and hung requests, when you mention the threshold, mention that the threshold can be configured (you've done it for slow requests but not for hung requests). Then add another short paragraph after the hung request paragraph that points them to the feature topic for how to configure the feature and for examples on how to adjust the thresholds.
- There's something not quite right in the syntax of the link so it's not rendering in HTML. Is it missing the link text maybe?
- Remove the triangular brackets when you mention elements or attributes (it's not technically correct to use them on attributes at all, but even for elements where it's accurate, it's unnecessarily cluttered). So say "`slowRequestThreshold` attribute" instead of "`<slowRequestThreshold>` attribute".
- Try to avoid using the name of an attribute etc in a sentence (for one thing, it doesn't translate, but it's also harder to read). eg, instead of "If the request exceeds the `hungRequestThreshold`", say "If the request exceeds the hung request threshold". If you think it's important to make clear which configuration value that refers to, you could always put it as "If the request exceeds the hung request threshold (`hungRequestThreshold`)" on first mention in a paragraph/section. That might be helpful in this topic to make clear in each section which configuration attribute value relates to the explanation in that section?

**Comment by ManasiGandhi** [comment] 2020-06-24 18:24
@lauracowen I worked on your suggestions. Can you review the draft https://draft-openlibertyio.mybluemix.net/docs/ref/general/#requestTiming.html?
    

- [x] Give the feature its proper name each time you mention it (ie " Request Timing feature"), instead of "requestTiming feature".

  

- [x]   Remove the 'Configure...' section. This info is in the feature topic. Instead, in the paragraphs above about slow requests and hung requests, when you mention the threshold, mention that the threshold can be configured (you've done it for slow requests but not for hung requests). Then add another short paragraph after the hung request paragraph that points them to the feature topic for how to configure the feature and for examples on how to adjust the thresholds.

  

- [x]   There's something not quite right in the syntax of the link so it's not rendering in HTML. Is it missing the link text maybe?

   

- [x] Remove the triangular brackets when you mention elements or attributes (it's not technically correct to use them on attributes at all, but even for elements where it's accurate, it's unnecessarily cluttered). So say "slowRequestThreshold attribute" instead of "<slowRequestThreshold> attribute".

  

- [x] Try to avoid using the name of an attribute etc in a sentence (for one thing, it doesn't translate, but it's also harder to read). eg, instead of "If the request exceeds the hungRequestThreshold", say "If the request exceeds the hung request threshold". If you think it's important to make clear which configuration value that refers to, you could always put it as "If the request exceeds the hung request threshold (hungRequestThreshold)" on first mention in a paragraph/section. That might be helpful in this topic to make clear in each section which configuration attribute value relates to the explanation in that section?

**Comment by dmuelle** [comment] 2020-06-25 20:10
# Peer Review

## Intro
`The Request Timing feature diagnoses the cause of slow web requests in application servers. `

I don't think this is accurate since the feature just gives information about the request and doesn't offer a reason "why" it is slow or hung, which is left to the user to infer from the message. I also think you could combine this with the next sentence and avoid using "Thus", which is somewhat archaic (though grammatically correct) Maybe: 

`The Request Timing feature helps you diagnose the causes of slow web requests by identifying requests that run longer than a specified threshold, `
------

`For each request that takes too long to complete, request timing prints a warning message along with the details captured for the request into the log file.`

Maybe

`For each request that exceeds the threshold, request timing prints a warning message into the log file with details about the request. `

might help to add an explanation of what a hung request is, other than a request that exceeds the hung threshold- ie they are requests that are taking longer than "slow" and require more analysis (or are in danger of not completing, I'm not sure how best to say it.)

-----
`For more information on how to configure the feature examples to adjust the thresholds in the Request Timing feature, see link:docs/ref/config/#requestTiming.html` <-- wrong link, no link text. Correct link is `/docs/ref/feature/#requestTiming-1.0.html`

Need to add the link text so it will render. Can also be more concise to say

`For more information, see the Request Timing feature.`

## Configure slow and hung request detection

In the feature manager example, why the two sets of three dots on either side of the feature? I haven't seen this in other examples

`For more details about default and configured thresholds in the Request Timing feature, see link:https://draft-openlibertyio.mybluemix.net/docs/ref/config/#requestTiming.html.` <--- needs link text (the Request Timing configuration element). Can also be shortened per above comment.


`three messages are displayed for any slow request at the interval specified by the slowRequestThreshold attribute`

Per acrolinx, change to

`three messages are displayed for any slow request at the interval that is specified by the slowRequestThreshold attribute`

## Detect hung requests


`Further Java cores are created only if new requests are detected to be hanging.`

maybe

`Further Java cores are created only if new hung requests are detected .`

-----

`The Request Timing feature runs all the time and enables slow and hung requests to be documented when they occur,...`

maybe

`Since the Request Timing feature runs all the time, it documents slow and hung requests as they occur,...`
-----
 `Users can view information about a slow request that completed with the request id and the amount of time it took for the request to complete.`

I'm not sure what this means- it sounds like you need to know both the ID and the time in order to view the info but I don't think that's correct. Also, use ID not id

**Comment by lauracowen** [comment] 2020-06-26 08:44
@ManasiGandhi I don't think your update file built properly. I can't see any of the changes you've ticked off on the draft site. eg the Configure section is still there and the link that isn't rendering correctly. It looks, from his comments, like @dmuelle did his peer review yesterday based on the same version as I reviewed the other day (which should be fine as I don't think there's a massive amount of new text you'd be adding anyway).

I've had a look in Github and I can see you made a commit with the message "Updates per Laura's edit suggestions" but that doesn't contain any of the changes either (that I can see). I think something must be going wrong when you're committing your changes on your laptop (maybe?). If you're not sure what's going wrong, have a chat with @Charlotte-Holt and see if she can see the problem (I don't use the editor you use so I don't know what the workflow is like from your perspective).

**Comment by ManasiGandhi** [comment] 2020-07-06 18:36
- [x] The Request Timing feature diagnoses the cause of slow web requests in application servers.

I don't think this is accurate since the feature just gives information about the request and doesn't offer a reason "why" it is slow or hung, which is left to the user to infer from the message. I also think you could combine this with the next sentence and avoid using "Thus", which is somewhat archaic (though grammatically correct) Maybe:

The Request Timing feature helps you diagnose the causes of slow web requests by identifying requests that run longer than a specified threshold, 

- [x] For each request that takes too long to complete, request timing prints a warning message along with the details captured for the request into the log file.

Maybe

For each request that exceeds the threshold, request timing prints a warning message into the log file with details about the request. 

- [x] might help to add an explanation of what a hung request is, other than a request that exceeds the hung threshold- ie they are requests that are taking longer than "slow" and require more analysis (or are in danger of not completing, I'm not sure how best to say it.)

- [x] For more information on how to configure the feature examples to adjust the thresholds in the Request Timing feature, see link:docs/ref/config/#requestTiming.html <-- wrong link, no link text. Correct link is /docs/ref/feature/#requestTiming-1.0.html

Need to add the link text so it will render. Can also be more concise to say

For more information, see the Request Timing feature.

- [x] In the feature manager example, why the two sets of three dots on either side of the feature? I haven't seen this in other  examples. 

- [x] three messages are displayed for any slow request at the interval specified by the slowRequestThreshold attribute

@dmuelle I worked on your peer edit suggestions.

Per acrolinx, change to

three messages are displayed for any slow request at the interval that is specified by the slowRequestThreshold attribute.


- [x] Further Java cores are created only if new requests are detected to be hanging.

maybe

Further Java cores are created only if new hung requests are detected . 

- [x] The Request Timing feature runs all the time and enables slow and hung requests to be documented when they occur,...

maybe

Since the Request Timing feature runs all the time, it documents slow and hung requests as they occur,... 

- [x] Users can view information about a slow request that completed with the request id and the amount of time it took for the request to complete.

**Comment by lauracowen** [comment] 2020-07-08 10:33
Looks good. Some formatting changes then I think you're done:

- Can you put the description of what the example shows after the example for each of the examples shown? eg for the first one, make the sentence "The following example..." the lead-in sentence (with a colon) before the example. Then move the "The `requestTiming` element..." sentence to straight after the example. I don't think we've done this consistently everywhere but I think it's easier to read.
- In XML, when there are no nested elements (eg in the first example), don't use a separate closing tag - instead, put a closing `/` in the end of the opening tag. eg `<requestTiming slowRequestThreshold="10s" hungRequestThreshold="10m" />` It's fine in the other two examples because they both have nested elements.

If you can do those, I think this is done. Thanks :)

**Comment by ManasiGandhi** [comment] 2020-07-08 16:38
@lauracowen here's the draft link https://draft-openlibertyio.mybluemix.net/docs/ref/general/#requestTiming.html

**Comment by lauracowen** [comment] 2020-07-08 17:05
- Good intro.
- Can you tweak wording where you link to the Request Timing feature so that it says "For more information about how to configure the Request Timing feature, see...". As the other topic doesn't really give a lot of background info, which is what the sentence currently implies - the rest of this topic is better for that.
- The last paragraph isn't part of the "Detect hung requests" section is it? It's nice having a summary paragraph but we don't seem to have them in many of our topics so I think move it up to just before the "Detect slow requests" heading and remove the other "Request Timing feature" link. But I think remove the sentences "The request Timing feature logs..." and "Users can view information..." as I think they duplicate what's already in the intro.

Other than that, looks good. Thanks.

**Comment by ManasiGandhi** [comment] 2020-07-14 18:24
@lauracowen Made the changes you suggested
- [ ] Can you tweak wording where you link to the Request Timing feature so that it says "For more information about how to configure the Request Timing feature, see...". As the other topic doesn't really give a lot of background info, which is what the sentence currently implies - the rest of this topic is better for that.

- [x] The last paragraph isn't part of the "Detect hung requests" section is it? It's nice having a summary paragraph but we don't seem to have them in many of our topics so I think move it up to just before the "Detect slow requests" heading and remove the other "Request Timing feature" link. But I think remove the sentences "The request Timing feature logs..." and "Users can view information..." as I think they duplicate what's already in the intro.

**Comment by lauracowen** [comment] 2020-07-15 11:13
Thanks.

- You missed a bit in the second point. Remove the two sentences from the paragraph you moved up: "The Request Timing feature logs..." and "Users can view information...".
- Also, can you move the "For more info" sentence from the paragraph above to the end of the para you moved. Then have a read of it to make sure it flows properly.

**Comment by ManasiGandhi** [comment] 2020-07-15 17:12
@lauracowen Thanks Laura. I made edits per your review.


    

- [x] You missed a bit in the second point. Remove the two sentences from the paragraph you moved up: "The Request Timing feature logs..." and "Users can view information...".

    

- [x] Also, can you move the "For more info" sentence from the paragraph above to the end of the para you moved. Then have a read of it to make sure it flows properly.

**Comment by ManasiGandhi** [comment] 2020-08-04 19:44
@chirp1 updated draft link https://draft-openlibertyio.mybluemix.net/docs/20.0.0.9/slow-hung-request-detection.html

**Comment by ManasiGandhi** [comment] 2020-09-03 21:08
New link to the draft https://draft-openlibertyio.mybluemix.net/docs/20.0.0.10/slow-hung-request-detection.html

**Comment by ManasiGandhi** [comment] 2020-10-05 16:28
@chirp1 Updated link to the draft https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/slow-hung-request-detection.html.

**Comment by ManasiGandhi** [comment] 2020-10-28 13:53
@chirp1 20.12 updated link https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/slow-hung-request-detection.html.

**Comment by dmuelle** [comment] 2022-10-26 16:35
https://openliberty.io/docs/latest/slow-hung-request-detection.html

**Closed** 2023-12-11 05:13 UTC
Labels: technical reviewed, strategist reviewed, 2Q20-1st 50, peer reviewed, published
