### ISSUE TITLE
SSO configuration with social media logins

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#895] opened 2020-01-07 19:00 UTC
From LC: Basic form-based authentication. See the KC topics on user registry. What is social login and what does it provide? Why is it beneficial to both the end-user (they can use their existing login details) and to the app hosting (don't need to set up/configure a user registry as the details are all held by the social media company's user registry)? 

Later in the topic, mention that it uses the Open ID Connect client standard - there's an OIDC Client feature too but the social login one is easier to use and provides most likely needed capability. Frame the topic to encourage the use of the social login feature instead of the OIDC Client feature, as that's the better feature to use. 

Explain how the OIDC process of authentication works (see https://developer.ibm.com/wasdev/docs/using-signed-json-web-tokens-jwts-secure-microservices/ and https://developer.ibm.com/wasdev/docs/using-access-tokens-secure-microservices/ for overviews). 

Come up with a standard diagram format, scenario (align with guides scenarios if possible), and wording to use across all the SSO topics so it's easy for a reader to compare the technologies doing the same thing in different ways.

Sources of information:
- https://www.ibm.com/support/knowledgecenter/SSD28V_liberty/com.ibm.websphere.wlp.core.doc/ae/twlp_sec_basic_registry.html 
- https://www.ibm.com/support/knowledgecenter/SSD28V_liberty/com.ibm.websphere.wlp.core.doc/ae/twlp_sec_ldap.html 
- https://www.ibm.com/support/knowledgecenter/SSD28V_liberty/com.ibm.websphere.wlp.core.doc/ae/rwlp_sec_dyn_upd.html 
- https://www.ibm.com/support/knowledgecenter/SSD28V_liberty/com.ibm.websphere.wlp.core.doc/ae/twlp_sec_sociallogin.html

**Comment by Rwalls1** [comment] 2020-02-07 16:01
Link to current draft (in progress): https://draft-openlibertyio.mybluemix.net/docs/ref/general/sso-config-social.html

**Comment by Rwalls1** [comment] 2020-03-05 21:04
@brutif Please review: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#sso-social-config.html

**Comment by brutif** [comment] 2020-03-05 21:36
Hi @Rwalls1  looks good, I have just a couple of minor suggestions - 
 - A new user is registered as a new user and then logged into the application. - Could this be omitted?
 - During the OIDC authorization process  - it should be "authentication".  The remote provider can say "yes this is Richard" but only the app can authorize Richard to access payroll.  (The long-ago choice of "oauth" as  a spec name was a confusing choice, in my opinion)

**Comment by Rwalls1** [comment] 2020-03-12 19:54
@brutif Please review the latest update: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#sso-social-config.html. The sentence "a new user is registered as a new user and then logged into the application" was intended to indicate the between a new user logging in and a current user. I combined that sentence with the preceding sentence to make that distinction clearer but let me know if you think if that is unnecessary.

**Comment by brutif** [comment] 2020-03-13 14:05
@Rwalls1 looks good! In some places you say "social media" and in others "social network" but that's fine with me.

**Comment by Rwalls1** [comment] 2020-03-13 17:42
@lauracowen Please review: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#sso-social-config.html

**Comment by lauracowen** [comment] 2020-04-03 10:07
Thanks, a good topic. Some specific comments:

- "...and selects a social media platform" - does it make sense to append "from a form" to this? To make it more concrete how the end-user selects the social media platform to log in with.
- "a current user of the platform gets access to the application" - shouldn't this be "a current user of the application gets access to the application". I think "platform" implies current versus new user of the social media platform but I don't think that's what you mean?
- can you avoid abbreviating terms? I know OP is commonly used (and it's fine to provide it in parentheses for additional recognition) but in the rest of the explanation still requires the reader to keep thinking back to what it means when we could just display "OpenID provider" for them to save them that effort. I think for OIDC - just say OpenID Connect. There are enough terms for the reader to learn and understand without doubling them with their shortened forms as well. :)
- "OIDC is a SSO method that enables applications to assign user authentication to authorization servers that return the application claims about the authenticated user and authentication event with a standard process to the application that provides the user access." - can you make this simpler (eg two sentences)?
- "The OpenID provider (OP) is an authorization server that implements OIDC, can authenticate a user, return claims about the authenticated user, and the authentication event to a relying party or application." - again, I think this is complex to mentally parse and the parts of the list aren't parallel.
- JWT is ok but use "JSON Web Token (JWT)" at least on the first mention.
- "To use OIDC, the application must be configured to enable the feature. However, if you use the Social Media Login feature, the entire OIDC authorization process is handled by the social media platform, which makes the process simpler." The first sentence implies you need to explicitly enable the OIDC feature in order to enable the Social Media Login feature, but I don't think that's the case. I think this paragraph is obliquely referring to the fact that SML feature is an easier way to enable the OIDC capability in your app. I think you can remove "To use OIDC, the application must be configured to enable the feature. However, " and then just add the last bit of that sentence as a new sentence on the end of the paragraph before ("If you use the Social Media Login feature,..."). Does that work?
- "you can choose between available social media login providers to authenticate yourself for a protected resource request." I think that should be "the end user can choose.......to log in." - The audience of this topic is the developer writing the app so "you" implies the developer. But also, an end-user wouldn't "authenticate yourself for a protected resource request." - they'd just "log in." or "log in to the application".
- Similarly "you are automatically redirected " should be "the end user is automatically redirected". Check the rest of the topic for similar instances and make sure the person is correct.
- "The options that appear on the default selection form are only the providers that are configured to protect the original resource request. " -> something like "The social media login providers that are displayed to the end user on the selection form are, by default, only the providers that are configured in the application to protect the original resource request. " (for clarity of what all the objects in the sentence are referring to). In general, make sure the language is accessible to readers and it's clear what is being referred to.
- Can you remove the configuration example and, instead, point them to the feature (autogen) topic for an example of single versus multiple social media providers. Then briefly explain that you can apply authentication filters and why they're useful, and then link to the autogen topic again for an example of that too.
- "...you can specify the location of your own selection form..." - I think the point is not that you might choose a different location but that you might choose a different form, so it's more that "You can provide your own custom selection form if you do not want to use the selection form that is provided with Open Liberty. Create your own selection form then specify its location in (where?). Any custom selection form needs to receive the following...etc" (be consistent in using either "form" or "page" - I think "form" works better because it's more specific but mainly don't switch words back and forth, though "a valid web page" is fine even if you use "form").
- Can you put the list of HTTP request parameters into a simple 2-column table. Then put the paragraph starting "When a protected resource request.." after the table.
- Is there something missing after "is a JSON object with the following entries:"?

**Comment by Rwalls1** [comment] 2020-04-14 14:33
@lauracowen Please review the latest update: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#sso-social-config.html

**Comment by lauracowen** [comment] 2020-05-05 17:51
Great, thanks.

**Comment by lauracowen** [comment] 2020-06-05 12:23
Hi Richard,

Alasdair and I took a look at some of the SSO topics last night and we agreed we need to make some changes to how the SSO info is presented. We currently have too much info about the abstract concepts that people could better obtain elsewhere. I'm going to chat with Charlotte about it this afternoon but please can you hold off working on this topic in the meantime?

Thanks,

Laura

**Comment by lauracowen** [comment] 2020-06-09 17:45
Superceded by #1676 so I'm closing this issue.

**Closed by lauracowen** 2020-06-09 17:45 UTC
Labels: 2Q20-1st 50, concept, technical reviewed

**Comment by chirp1** [comment] 2020-10-21 01:39
@Rwalls1 Hi Richard,
Here are my comments:
- For "Social Media Login is a form of SSO that enables ..." the link is to a commercial site. Instead, link to standards/specifications,  for  OAuth and OpenID Connect, which are mentioned later in the same paragraph..
- For "JSON Web Token (JWT) is a standard that" , change the link to the JWT spec instead of a website.
- For "shared between applications. ", is it more than two applications? Should  "between" be "among"? Same questions for " "by SSO between different microservice applications."
- I see that you used "between" 9 times in the topic. Would you go through all 9 occurrences and make sure that you are using "between" and "among" correctly? I think at least one or two of them should be "among".
- Update the link for "Guide: Securing microservices with JSON Web Tokens. " as the link goes to a draft server and gets a 404.
- Avoid need to, needs to, needing to across your topics as the phrases add in unnecessary words. So, rewrite "of needing to use a:" so that you don't use "needing".
- Use active voice more. For instance, rewrite "SPNEGO can be used to provide SSO ..." and "SPNEGO can also be configured".
- For "SAML is a standard that offers... " replace the SAML link since it is to some commercial company. Replace it with a link to the specification. 
- Spell out SPNEGO, SAML, and LTPA on first occurrence.
- The link for LTP in "LTPA provides a method of SSO " is a link to a commercial company. Don't use a commercial company. Also, I think LTPA is an IBM technology, including for tWAS and Liberty, isn't it?
- For "when the Application Security feature is enabled ", how about if you  link to the Application Security feature?
- Research "Active Directory server " and make changes as appropriate. I don't think "Active Directory" is a server. I think it is a service, maybe on a Windows server??
